name: digital_twin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy>=2.2
  - pandas>=2.3
  - scikit-learn>=1.7
  - scipy>=1.15
  - matplotlib>=3.10
  - joblib>=1.5
  - networkx>=3.4
  - pip
  - pip:
      - torch>=2.0
      - torchvision
      - torchaudio
      - pyyaml>=6.0
      - dowhy>=0.14
      - tqdm>=4.67
      - ipykernel>=7.2
      - jupyter_client>=8.8
